export const REQUEST_ROLES_START = "REQUEST_ROLES_START";
export const REQUEST_ROLES_SUCCESS = "REQUEST_ROLES_SUCCESS";

export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const CHANGE_SCREEN = "CHANGE_SCREEN";